name: Release a CV

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  render-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rename Resume File (Preserving Type)
        run: |
          for file in *Resume*.public.pdf; do
            if [[ -f "$file" ]]; then
              # Extracts "Music" or "Software" from the filename
              resume_type=$(echo "$file" | grep -oE "(Music|Software) Resume")

              if [[ -n "$resume_type" ]]; then
                new_name="Alexander_Dumouchelle_$resume_type.pdf"
                mv "$file" "$new_name"
                echo "Renamed $file to $new_name"
              else
                echo "Could not determine resume type for $file"
              fi
            else
              echo "No matching file found."
            fi
          done

      - name: Get latest tag and increment
        id: tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          IFS='.' read -r -a parts <<< "${latest_tag//v/}"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}
          new_patch=$((patch + 1))
          new_tag="v$major.$minor.$new_patch"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          echo "Generated new tag: $new_tag"

      - name: Release to public repo
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.new_tag }}
          files: "*.public.*"
          generate_release_notes: false
          make_latest: true
