name: Release a CV

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  render-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rename Resume File (Preserving Type)
        run: |
          for file in *Resume*.public.pdf; do
            if [[ -f "$file" ]]; then
              # Extracts "Music" or "Software" from the filename
              resume_type=$(echo "$file" | grep -oE "(Music|Software)")

              if [[ -n "$resume_type" ]]; then
                new_name="Alexander_Dumouchelle_${resume_type}_Resume_Public.pdf"
                mv "$file" "$new_name"
                echo "Renamed $file to $new_name"
              else
                echo "Could not determine resume type for $file"
              fi
            else
              echo "No matching file found."
            fi
          done

      - name: Ensure tags are fetched
        run: git fetch --tags --force

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          use_api: true

      - name: Release to public repo
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          files: "*.*"
          generate_release_notes: false
          make_latest: true
