name: Release a CV

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  render-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rename Resume File (Preserving Type)
        run: |
          for file in *Resume*.public.pdf; do
            if [[ -f "$file" ]]; then
              # Extracts "Music" or "Software" from the filename
              resume_type=$(echo "$file" | grep -oE "(Music|Software) Resume")

              if [[ -n "$resume_type" ]]; then
                new_name="Alexander_Dumouchelle_$resume_type_Resume_public.pdf"
                mv "$file" "$new_name"
                echo "Renamed $file to $new_name"
              else
                echo "Could not determine resume type for $file"
              fi
            else
              echo "No matching file found."
            fi
          done

      - name: Ensure tags are fetched
        run: git fetch --tags --force

      - name: Get Latest Tag and Increment
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
          IFS='.' read -r -a parts <<< "${latest_tag//v/}"
          major=${parts[0]:-0}
          minor=${parts[1]:-1}
          patch=${parts[2]:-0}
          patch=$((patch + 1))
          new_tag="v$major.$minor.$patch"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Release to public repo
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.new_tag }}
          files: "*.*"
          generate_release_notes: false
          make_latest: true
